#!/usr/bin/env bash
# inject-contact.sh — 联系方式卡片注入器（单一真实源）
#
# 2026-07 起：联系方式卡片只在仓库根 README.md 保留，不再注入专题或内容文章。
# 本脚本不再扫描全量内容文章；只用于显式刷新根 README.md 的卡片。
# 占位符: <!-- CONTACT-START --> ... <!-- CONTACT-END -->
# 可重入(幂等):
#   - 已有占位符: 原地替换块内容(保留卡片在文件中的位置)。
#   - 无占位符: 报错，避免把卡片误放到首屏。
#   - 重复运行: 结果完全一致, 不会堆叠。
# 根 README.md 的卡片放在任务导航之后(非首屏), 用占位符标记;
# 显式对该文件运行脚本会原地更新, 不会移动位置。
# 改联系方式只需改 docs/_snippets/contact.html, 再对根 README.md 跑本脚本。
#
# Usage:
#   ./scripts/inject-contact.sh                                    # 已禁用全量注入，仅打印提示
#   ./scripts/inject-contact.sh README.md                           # 刷新根 README 的卡片

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

SNIPPET="docs/_snippets/contact.html"
START="<!-- CONTACT-START -->"
END="<!-- CONTACT-END -->"
NOTE="<!-- Auto-generated by scripts/inject-contact.sh — 单一真实源: ${SNIPPET} -->"

[ -f "$SNIPPET" ] || { echo "ERROR: snippet not found: $SNIPPET"; exit 1; }

if [ $# -gt 0 ]; then
    FILES=("$@")
else
    # 2026-07 起：内容文章不再注入卡片，全量注入已禁用。
    echo "ℹ️ 专题与内容文章不再注入联系方式卡片（仅根 README.md 保留）。"
    echo "   刷新根 README 卡片请运行：./scripts/inject-contact.sh README.md"
    exit 0
fi

updated=0
invalid=0

for f in "${FILES[@]}"; do
    [ -f "$f" ] || { echo "ERROR: not a file: $f"; invalid=$((invalid+1)); continue; }
    [ "$f" = "README.md" ] || { echo "ERROR: contact card only belongs in root README.md: $f"; invalid=$((invalid+1)); continue; }

    if grep -qF "$START" "$f"; then
        # 已有占位符: 原地替换块内容(保留卡片在文件中的位置)
        tmp="$(mktemp)"
        awk -v START="$START" -v ENDMARK="$END" -v NOTE="$NOTE" -v SNIPPET="$SNIPPET" '
            BEGIN { skip=0 }
            $0==START {
                print START; print NOTE
                while ((getline line < SNIPPET) > 0) print line
                close(SNIPPET)
                print ENDMARK
                skip=1; next
            }
            $0==ENDMARK { skip=0; next }
            skip { next }
            { print }
        ' "$f" > "$tmp"
        mv "$tmp" "$f"
        updated=$((updated+1))
    else
        echo "ERROR: contact markers are missing in root README.md"
        echo "       Add $START and $END after the task navigation, then rerun."
        invalid=$((invalid+1))
    fi
done

if [ "$invalid" -gt 0 ]; then
    echo "❌ contact 注入失败: ${invalid} 个错误，更新 ${updated}"
    exit 1
fi

echo "✅ contact 注入完成: 更新 ${updated} (共处理 ${#FILES[@]} 个文件)"
echo "   改联系方式请编辑: ${SNIPPET}  →  再跑: ./scripts/inject-contact.sh README.md"
